/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  plugins: [require('@tailwindcss/forms')],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#bdc7d6',
        'secondary': '#325f9c',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#2d476f',
        'primary-fixed-dim': '#aec7f6',
        'error': '#ba1a1a',
        'primary-fixed': '#d6e3ff',
        'tertiary': '#030b15',
        'on-background': '#0b1c30',
        'tertiary-fixed': '#d9e3f2',
        'outline-variant': '#c4c6cf',
        'surface-container': '#e5eeff',
        'primary-container': '#002147',
        'surface-bright': '#f8f9ff',
        'primary': '#000a1e',
        'on-secondary-fixed': '#001b3c',
        'secondary-fixed': '#d5e3ff',
        'inverse-primary': '#aec7f6',
        'on-tertiary-container': '#7f8997',
        'tertiary-container': '#18222d',
        'inverse-on-surface': '#eaf1ff',
        'surface-dim': '#cbdbf5',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-surface': '#0b1c30',
        'surface-tint': '#465f88',
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#154985',
        'surface-container-highest': '#d3e4fe',
        'on-primary-container': '#708ab5',
        'outline': '#74777f',
        'on-primary-fixed': '#001b3d',
        'inverse-surface': '#213145',
        'secondary-fixed-dim': '#a7c8ff',
        'secondary-container': '#90bafd',
        'on-tertiary-fixed': '#131c27',
        'surface': '#f8f9ff',
        'surface-container-low': '#eff4ff',
        'background': '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#44474e',
        'on-secondary-fixed-variant': '#114783',
        'on-tertiary-fixed-variant': '#3e4853',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-md': '16px',
        'container-max': '1440px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'unit': '4px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'mono-md': ['JetBrains Mono'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'mono-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
      },
      boxShadow: {
        'level-2': '0px 4px 12px rgba(0, 33, 71, 0.05)',
        'level-3': '0px 8px 24px rgba(0, 33, 71, 0.1)',
      },
    },
  },
}
